import { describe, expect, it } from "vitest";

import {
  assertUniqueSitemapUrls,
  getRobotsTxt,
  getSitemapEntries,
  getSitemapUrls,
  getSitemapXml,
} from "../../src/data/sitemap";
import { sitemapDates } from "../../src/data/sitemap-dates";
import { siteUrl } from "../../src/data/metadata";
import { toolRegistry } from "../../src/data/tools";

describe("sitemap generation", () => {
  it("contains the homepage, public information pages, and available registry tools", () => {
    const expectedUrls = [
      new URL("/", siteUrl).toString(),
      new URL("/tools/", siteUrl).toString(),
      new URL("/flows/", siteUrl).toString(),
      new URL("/roadmap/", siteUrl).toString(),
      new URL("/privacy/", siteUrl).toString(),
      new URL("/terms/", siteUrl).toString(),
      new URL("/about/", siteUrl).toString(),
      new URL("/request-a-gizlet/", siteUrl).toString(),
      ...toolRegistry
        .filter((tool) => tool.launchStatus === "available")
        .map((tool) => new URL(tool.path, siteUrl).toString()),
    ];

    expect(getSitemapUrls()).toEqual(expectedUrls);
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/</loc>");
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/tools/</loc>");
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/flows/</loc>");
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/roadmap/</loc>");
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/privacy/</loc>");
    expect(getSitemapXml()).toContain("<loc>https://gizlet.app/request-a-gizlet/</loc>");
    expect(getSitemapXml()).toContain("json-ld-generator");
    expect(getSitemapXml()).toContain("json-formatter");
  });

  it("gives every page a lastmod, so no page is left without one by accident", () => {
    // The dates are generated by scripts/generate-sitemap-dates.mjs, which
    // declares the files behind each page. A new Gizlet reaches the sitemap
    // through the registry and would otherwise slip in undated: this is what
    // makes that a failing test rather than a quiet omission.
    const undated = getSitemapEntries().filter((entry) => entry.lastModified === undefined);

    expect(undated.map((entry) => entry.pathname)).toEqual([]);
  });

  it("dates every page plausibly, and dates nothing it does not serve", () => {
    const today = new Date().toISOString().slice(0, 10);

    for (const entry of getSitemapEntries()) {
      expect(entry.lastModified, entry.pathname).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      // A date in the future is a generator reading the wrong clock, and a
      // date a crawler will not believe.
      expect(entry.lastModified! <= today, entry.pathname).toBe(true);
    }

    // The generated file is keyed by the pathnames the sitemap actually holds,
    // so a route that was renamed cannot leave its old date behind.
    expect(Object.keys(sitemapDates).sort()).toEqual(
      getSitemapEntries()
        .map((entry) => entry.pathname)
        .sort(),
    );
  });

  it("writes the date into the XML beside the location", () => {
    const xml = getSitemapXml();

    expect(xml).toContain(
      `<loc>https://gizlet.app/privacy/</loc><lastmod>${sitemapDates["/privacy/"]}</lastmod>`,
    );
    // Every entry carries exactly one of each, and no entry carries an empty one.
    expect((xml.match(/<loc>/g) ?? []).length).toBe(getSitemapUrls().length);
    expect((xml.match(/<lastmod>/g) ?? []).length).toBe(getSitemapUrls().length);
    expect(xml).not.toContain("<lastmod></lastmod>");
  });

  it("rejects duplicate URLs so they cannot be emitted during a build", () => {
    expect(() =>
      assertUniqueSitemapUrls(["https://gizlet.app/", "https://gizlet.app/"]),
    ).toThrow("Duplicate sitemap URLs generated");
  });
});

describe("robots.txt generation", () => {
  it("allows crawling and points crawlers to the production sitemap", () => {
    expect(getRobotsTxt()).toBe(
      "User-agent: *\nAllow: /\n\nSitemap: https://gizlet.app/sitemap.xml\n",
    );
  });
});
